Repository WasteOfADrumBum/project-iii, pull requests merged in 2020-12, with the labels that each got.

#119 Joshua spectre laptop
  client/src/App.js
  client/src/components/accordion/Accordion.jsx
  client/src/components/loops/PlacesLoop.jsx
  client/src/components/loops/VehicleLoop.jsx
  client/src/pages/Profile.jsx
  client/src/utils/UserContext.js
  server/controllers/userController.js
  server/models/UserInfo.js
  server/routes/apiRoutes.js
  server/seeders/seedDB.js
Labels: bug, enhancement

#120 Jf formdev
  client/src/pages/Vehicle.jsx
Labels: bug, enhancement

#121 updates
  client/src/assets/styles/landingpage.scss
  client/src/components/accordion/Accordion.jsx
  client/src/components/modal/Modal.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/Profile.jsx
Labels: bug, documentation

#126 Max dev
  client/src/components/accordion/Accordion.jsx
  client/src/components/address/MapContainer.jsx
  client/src/pages/LetsGo.jsx
Labels: help wanted
