Repository WasteOfADrumBum/project-iii, pull requests merged in 2020-11, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#9 Update README.md
  README.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation

#18 Relocated README.md to root directory
  README.md
Labels: bug, documentation

#26 +Login Page
  client/debug.log
  client/src/assets/images/login-bg.jpg
  client/src/assets/styles/login.scss
  client/src/pages/LandingPage.jsx
  client/src/pages/Login.jsx
Labels: enhancement

#27 Content Creation
  README.md
  client/src/App.js
  client/src/assets/images/letsgo-bg.jpg
  client/src/assets/images/profile-bg.jpg
  client/src/assets/images/register-bg.jpg
  client/src/assets/images/vehicle-bg.jpg
  client/src/assets/styles/letsgo.scss
  client/src/assets/styles/register.scss
  client/src/assets/styles/vehicle.scss
  client/src/components/navbar/NavBar.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/MyPlaces.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/Vehicle.jsx
  client/src/pages/index.js
Labels: documentation, enhancement, help wanted, question

#29 Max dev
  client/src/components/address/addressCapture.jsx
  client/src/components/address/addressForm.jsx
  client/src/components/address/addressInput.jsx
  client/src/components/address/addressItem.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Vehicle.jsx
Labels: enhancement

#30 Updates with new AddressForm Component
  client/src/App.js
  client/src/assets/styles/letsgo.scss
  client/src/pages/Address.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/index.js
Labels: enhancement

#40 move travis
  .travis.yml
Labels: bug

#44 added places.name to userinfo model
  client/models/UserInfo.js
Labels: bug

#45 image update
  client/public/assets/images/arlene-200x200.jpg
  client/public/assets/images/arlene-avatar.png
  client/public/assets/images/arlene.jpg
  client/public/assets/images/jim-200x200.jpg
  client/public/assets/images/jim-avatar.png
  client/public/assets/images/jim.jpg
  client/public/assets/images/josh-200x200.jpg
  client/public/assets/images/josh.jpg
  client/public/assets/images/joshua-avatar.png
  client/public/assets/images/mark-200x200.jpg
  client/public/assets/images/mark-avatar.png
  client/public/assets/images/mark.jpg
  client/public/assets/images/max-200x200.jpg
  client/public/assets/images/max-avatar.png
  client/public/assets/images/max.jpg
  client/src/components/carousel/Carousel.jsx
  client/src/pages/LetsGo.jsx
Labels: bug, enhancement

#48 Contact Page Complete
  client/debug.log
  client/public/assets/images/jim.jpg
  client/src/assets/styles/contact.scss
  client/src/components/address/addressInput.jsx
  client/src/pages/Contact.jsx
Labels: enhancement

#50 Profile Page
  client/debug.log
  client/src/assets/canvasjs.min.js
  client/src/assets/canvasjs.react.js
  client/src/assets/images/footprint-bg.jpg
  client/src/assets/styles/contact.scss
  client/src/assets/styles/profile.scss
  client/src/components/charts/ColumnChart.jsx
  client/src/components/charts/DoughnutChart.jsx
  client/src/components/footer/Footer.jsx
  client/src/components/navbar/NavBar.jsx
  client/src/pages/Contact.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
Labels: enhancement, question

#68 Backend update.
  .gitignore
  LICENSE
  app.js
  package-lock.json
  package.json
  server/controllers/AppController.js
  server/controllers/AuthController.js
  server/controllers/baseController.js
  server/controllers/errorController.js
  server/controllers/userController.js
  server/index.js
  server/models/UserInfo.js
  server/routes/apiRoutes.js
  server/seeders/seedDB.js
  server/server.js
  server/utils/apiFeatures.js
  server/utils/appError.js
Labels: bug, enhancement, help wanted, question

#71 SERVER FIXES - PLEASE READ BEFORE MERGEING
  .env
  .gitignore
  client/src/components/navbar/NavBar.jsx
  client/src/pages/Login.jsx
  client/src/pages/Register.jsx
  server/app.js
  server/controllers/AuthController.js
  server/controllers/userController.js
  server/models/UserInfo.js
  server/models/index.js
  server/routes/apiRoutes.js
  server/seeders/seedDB.js
  server/server.js
Labels: bug, enhancement, help wanted, question

#73 +Quotes Component
  client/src/assets/styles/index.scss
  client/src/components/quote/Quote.jsx
  client/src/components/quote/QuoteAndAuthor.js
  client/src/components/quote/QuoteDB.js
  client/src/db/factData.json
  client/src/index.js
  client/src/pages/Register.jsx
  server/routes/apiRoutes.js
Labels: bug, enhancement

#77 Login Token Fix
  .env
  client/src/pages/LandingPage.jsx
  client/src/pages/Login.jsx
  server/.env
  server/controllers/AuthController.js
  server/routes/apiRoutes.js
  server/server.js
Labels: bug, documentation, help wanted

#78 +Vehicle Page Update
  client/src/assets/styles/vehicle.scss
  client/src/pages/Vehicle.jsx
Labels: documentation, enhancement, help wanted

#79 debugging authcontroller
  client/src/pages/Login.jsx
  server/controllers/AppController.js
  server/controllers/AuthController.js
  server/models/UserInfo.js
  server/models/VehicleInfo.js
  server/models/index.js
  server/routes/apiRoutes.js
Labels: bug

#80 Updated comments for troubleshooting login errors
  client/src/pages/Login.jsx
  server/controllers/AuthController.js
  server/routes/apiRoutes.js
Labels: bug

#81 LOGIN FIX
  server/models/UserInfo.js
  server/routes/apiRoutes.js
Labels: bug

#82 LOGIN/AUTH FIX
  client/src/pages/LandingPage.jsx
  client/src/pages/Login.jsx
  server/controllers/AuthController.js
  server/models/UserInfo.js
  server/routes/apiRoutes.js
  server/seeders/seedDB.js
Labels: bug

#84 admin fix
  client/src/pages/LandingPage.jsx
  server/controllers/AdminController.js
  server/routes/adminRoutes.js
Labels: bug

#85 working login and auth... finally
  README.md
  client/src/core/utils/apiCalls.js
  client/src/pages/LandingPage.jsx
  client/src/pages/Login.jsx
  server/app.js
  server/controllers/AuthController.js
  server/routes/adminRoutes.js
  server/routes/apiRoutes.js
  server/routes/authRoutes.js
Labels: bug

#87 +LOGOUT
  client/src/components/logout/Logout.jsx
  client/src/components/navbar/NavBar.jsx
  server/app.js
  server/controllers/AuthController.js
Labels: enhancement

#90 +Client Side User Verification Added To Utils
  client/src/pages/Contact.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/Results.jsx
  client/src/pages/Vehicle.jsx
  client/src/utils/UserVerify.js
  client/src/utils/routeController.js
Labels: enhancement

#91 +React.useEffect
  client/src/pages/Contact.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/Results.jsx
  client/src/pages/Vehicle.jsx
Labels: bug, enhancement

#92 Login route redirects
  README.md
  client/src/pages/LandingPage.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/Results.jsx
  client/src/pages/Vehicle.jsx
  client/src/utils/UserVerify.js
  server/controllers/AppController.js
Labels: enhancement

#94 Joshua project iii branch
  client/src/App.js
  client/src/components/navbar/NavBar.jsx
  client/src/pages/Login.jsx
Labels: enhancement

#96 +Accordion Component on LetsGo page
  client/package-lock.json
  client/package.json
  client/src/components/accordion/Accordion.jsx
  client/src/pages/LetsGo.jsx
  server/models/UserInfo.js
  server/seeders/seedDB.js
Labels: enhancement

#100 +Improvments
  client/package-lock.json
  client/package.json
  client/public/assets/images/placeholder-profile-sq.jpg
  client/src/assets/styles/profile.scss
  client/src/components/address/AddressAutocomplete.jsx
  client/src/components/address/MapContainer.jsx
  client/src/components/modal/Modal.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/utils/UserDataMount.js
  server/controllers/AuthController.js
  server/seeders/seedDB.js
Labels: bug, enhancement

#103 Dependency fix & accordion update
  client/package-lock.json
  client/package.json
  client/src/assets/styles/accordion.scss
  client/src/assets/styles/letsgo.scss
  client/src/components/accordion/Accordion.jsx
  client/src/components/accordion/AccordionText.jsx
  client/src/components/address/MapContainer.jsx
  client/src/index.js
  client/src/pages/LandingPage.jsx
  client/src/pages/LetsGo.jsx
  package-lock.json
  package.json
Labels: bug

#104 User data displayed on page
  client/src/components/address/MapContainer.jsx
  client/src/pages/Contact.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/LetsGo.jsx
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/Vehicle.jsx
  client/src/utils/UserDataMount.js
  client/src/utils/UserVerify.js
  server/controllers/AppController.js
  server/controllers/AuthController.js
  server/routes/apiRoutes.js
Labels: bug, enhancement

#105 VehicleLoop.jsx
  client/src/components/loops/VehicleLoop.jsx
  client/src/pages/Profile.jsx
Labels: enhancement

#107 +Utils for Vehicle Form Options
  client/src/components/address/AddressAutocomplete.jsx
  client/src/components/loops/VehicleLoop.jsx
  client/src/components/modal/Modal.jsx
  client/src/pages/Login.jsx
  client/src/pages/Vehicle.jsx
  client/src/utils/cylinders.js
  client/src/utils/makes.js
  client/src/utils/model.js
  client/src/utils/transmission.js
  client/src/utils/year.js
Labels: bug, enhancement, help wanted, question

#109 updates
  client/src/components/accordion/Accordion.jsx
  client/src/components/address/MapContainer.jsx
  client/src/components/loops/VehicleLoop.jsx
  client/src/components/modal/Modal.jsx
  client/src/index.js
  client/src/pages/LetsGo.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Register.jsx
  client/src/pages/Vehicle.jsx
  client/src/utils/UserContext.js
Labels: enhancement

#114 Joshua project iii branch
  client/src/App.js
  client/src/components/logout/Logout.jsx
  client/src/components/loops/PlacesLoop.jsx
  client/src/components/navbar/NavBar.jsx
  client/src/index.js
  client/src/pages/Login.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Vehicle.jsx
  client/src/utils/UserContext.js
  client/src/utils/cylinders.js
  client/src/utils/makes.js
  client/src/utils/model.js
  client/src/utils/transmission.js
Labels: enhancement
